### PR TITLE
Subscription update

### PR DESCRIPTION
**Pull request by meomancer**

### CODE REVIEW

**Comment by Andrevdb** [comment]
Do you need me to merge this @meomancer ?

**Comment by meomancer** [comment]
hi @Andrevdb 
Not yet

DONE:
- Cancel and Refund when the subscription still 1 day 
- Cancel next payment when the subscription is already 1 day  
- Change payment method without reselecting subscription
- Resubscribe if the subscription is not active
- Change subscription without change payment method
- Make 1 organisation to 1 customer
- All payments and invoices go to the customer

TODO:
- When change subscription, do prorate payment
- When the prorate is not enough, invoicing to customer
- When the prorate is enough or more than enough, refund the remaining

Hi @Andrevdb @timlinux 
Do you have any inputs for these?

**Comment by meomancer** [comment]
**Subscription page**
Selection_044

**Comment by meomancer** [comment]
**When cancel, if the creation is still today**
Selection_045

After canceled
Selection_046

It is refunded
Selection_047

**Comment by meomancer** [comment]
If already more than 1 day
Selection_048

After cancelled
Selection_049

The subscription is still active but no future invoice
Selection_050

**Comment by meomancer** [comment]
Click Edit
Selection_051

And just put new card
Selection_052

**Comment by Andrevdb** [comment]
Hi @meomancer, great work thank you so much. Here are some minor grammar edits:
image
user(s) could be plural if the number is more than 1.

**Comment by meomancer** [comment]
The above image has been fixed

I'm going to merge this for now @Andrevdb 
We can deploy it on staging later

**Pull request merged**
