### PR TITLE
update docker file

### PR DESCRIPTION
**Pull request by voogt**
This is the PR for ticket #30

### CODE REVIEW

**Review by osundwajeff — COMMENTED** [review]
Hi @voogt 

I have tested this on my local and this is what I got:

image

Fixed by:

image

Then this issue:

image

Fixed by:

image

After fixing those two errors, this occurs:

image

**Comment by voogt** [comment]
Hi @osundwajeff I uploaded a fix can you try again?

**Comment by osundwajeff** [comment]
Hi @voogt, the fix works fine.

**Comment by osundwajeff** [comment]
@voogt you can checkout this PR #54  for the fixes I made.

**Pull request merged**
